HOUSE_INFO_CALLBACK = "hi"
HOUSE_LIST_CALLBACK = "hl"
HOUSE_HELP_CALLBACK = "hh"

CHAT_RULES_CALLBACK = "cr"

INVITATION_APPROVE_CALLBACK = "ia"
INVITATION_REJECT_CALLBACK = "ir"
INVITATION_PEND_CALLBACK = "ip"

GOI_ACCEPT = "ga"
GOI_DECLINE = "gd"

JEWISH_HELP_CALLBACK = "jh"

ROLE_HELP_CALLBACK = "rh"

MAIN_HELP_CALLBACK = "mh"

COMMANDS_HELP_CALLBACK = "ch"

WHY_HELP_CALLBACK = "wh"

VERSION = "2.0"
