HOUSE_INFO_CALLBACK = "hi"
HOUSE_LIST_CALLBACK = "hl"
HOUSE_HELP_CALLBACK = "hh"

CHAT_RULES_CALLBACK = "cr"

JEWISH_HELP_CALLBACK = "jh"

ROLE_HELP_CALLBACK = "rh"

MAIN_HELP_CALLBACK = "mh"

VERSION = "1.0"
